stages:
  - install
  - build
  - release

# 第一阶段：安装依赖
install:
  stage: install
  image: node:20 # 使用 Node.js 环境镜像，可以根据需要调整版本
  script:
    - npm config set registry https://registry.npmmirror.com
    - npm install
  artifacts:
    paths:
      - node_modules # 保存 node_modules 供后续步骤使用

# 第二阶段：构建
build:
  stage: build
  image: node:20
  script:
    - npm run build-only
    - tar -czvf dist.tar.gz -C dist . # 打包 dist 文件夹内容
  artifacts:
    paths:
      - dist.tar.gz # 保存压缩包为 GitLab 产物供后续步骤使用

# 第三阶段：发布
release:
  stage: release
  # image: alpine:latest # 使用轻量的 Alpine Linux 环境镜像
  script:
    - echo "done"
    # - apk add --no-cache openssh # 安装 SSH 客户端用于上传
    # - scp dist.tar.gz root@101.1.23.1:/home/project # 将压缩包上传到服务器指定目录
  dependencies:
    - build # 依赖 build 步骤中的产物
  only:
    - main # 只在 main 分支上运行
