image: node:20

stages:
  - install
  - build
  - release

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - echo "Stage 1 - 安装依赖"
    - echo "设置npm镜像源"
    - npm config set registry https://registry.npmmirror.com
    - echo "开始安装依赖"
    - npm install || exit 1

build:
  stage: build
  script:
    - echo "设置APT镜像源为阿里云"
    # 创建新的sources.list
    - echo "deb http://mirrors.aliyun.com/debian/ bookworm main non-free contrib" > /etc/apt/sources.list
    - echo "deb-src http://mirrors.aliyun.com/debian/ bookworm main non-free contrib" >> /etc/apt/sources.list
    - echo "deb http://mirrors.aliyun.com/debian-security bookworm-security main" >> /etc/apt/sources.list
    - echo "deb http://mirrors.aliyun.com/debian bookworm-updates main non-free contrib" >> /etc/apt/sources.list
    - echo "deb deb-src http://mirrors.aliyun.com/debian bookworm-updates main non-free contrib" >> /etc/apt/sources.list
    - echo "deb http://mirrors.aliyun.com/debian bookworm-backports main non-free contrib" >> /etc/apt/sources.list
    - echo "deb-src http://mirrors.aliyun.com/debian bookworm-backports main non-free contrib" >> /etc/apt/sources.list
    - echo "安装zip工具"
    - apt-get update && apt-get install -y zip
    - echo "Stage 2 - 构建产物"
    - npm run build-only || exit 1
    - echo "打包 dist 文件夹为 dist.zip"
    - zip -r dist.zip dist/  # 打包dist目录为zip文件
  artifacts:
    paths:
      - dist.zip  # 保存zip文件为产物

release:
  stage: release
  only:
    - main  # 只在main分支上运行release
  script:
    - echo "Stage 3 - 发布产物"
    - echo "上传dist.zip到指定端点"
    - |
      curl -X POST \
        -H "Authentication: $GITLAB_SYNC_TOKEN" \
        -F "dist=@./dist.zip" \
        $GITLAB_SYNC_ENDPOINT || exit 1
    - echo "创建GitLab Release"
    - |
      curl --fail --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
           --data "name=$CI_COMMIT_TITLE" \
           --data "tag_name=v$(date +'%Y.%m.%d')_$CI_COMMIT_SHORT_SHA" \
           --data "description=Gitlab流水线自动构建, 版本 v$(date +'%Y-%m-%d')_$CI_COMMIT_SHORT_SHA, 构建产物请前往流水线下载" \
           --data "ref=main" \
           "https://gitlab.54sher.com/api/v4/projects/$CI_PROJECT_ID/releases" || exit 1
    - echo "所有操作成功完成"
  dependencies:
    - build