stages:
  - install
  - build
  - release

# 第一阶段：安装依赖
install:
  stage: install
  image: node:20 # 使用 Node.js 环境镜像，可以根据需要调整版本
  script:
    - npm config set registry https://registry.npmmirror.com
    - npm install
  artifacts:
    paths:
      - node_modules # 保存 node_modules 供后续步骤使用

# 第二阶段：构建
build:
  stage: build
  image: node:20
  script:
    - npm run build-only
    - tar -czvf dist.tar.gz -C dist . # 打包 dist 文件夹内容
  artifacts:
    paths:
      - dist.tar.gz # 保存压缩包为 GitLab 产物供后续步骤使用

# 第三阶段：发布
release-server:
  stage: release
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh sshpass # 安装 ssh 和 sshpass
  script:
    - sshpass -p "$SERVER_PASSWORD" scp dist.tar.gz root@127.0.0.1:/home/project # 使用密码上传
  dependencies:
    - build
  only:
    - main

release-gitlab:
  stage: release
  image: node:20
  before_script:
    - apk add --no-cache openssh sshpass curl
  script:
    # 在 GitLab 上发布 Release
    - |
      curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
           --data "name=Release for $(date +'%Y-%m-%d')" \
           --data "tag_name=v$(date +'%Y.%m.%d')" \
           --data "description=自动发布的 Release" \
           --data "ref=main" \
           "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/releases"
  dependencies:
    - build
  only:
    - main