#使用node.js 20版本
image: node:20

# 设置缓存，避免每次都重新拉取node_modules
cache:
  paths:
    - node_modules/

# 定义流水线阶段
stages:
  - install
  - build
  - release

# 第一阶段：安装依赖
install:
  stage: install
  script:
    - echo "Stage 1 - 安装依赖"
    - echo "设置npm镜像源"
    - npm config set registry https://registry.npmmirror.com
    - echo "开始安装依赖"
    - npm install

# 第二阶段：构建
build:
  stage: build
  script:
    - echo "Stage 2 - 构建产物"
    - npm run build-only
    - echo "打包 dist 文件夹内容"
    # - tar -czvf dist.tar.gz -C dist .
  artifacts:
    paths:
      - dist/ # 保存压缩包为 GitLab 产物供后续步骤使用

release:
  stage: release
  script:
    # 在 GitLab 上发布 Release
    - echo "Stage 3 - 发布产物"
    - |
      curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
           --data "name=自动构建, 版本 v$(date +'%Y-%m-%d')_$CI_COMMIT_SHORT_SHA" \
           --data "tag_name=v$(date +'%Y.%m.%d')_$CI_COMMIT_SHORT_SHA" \
           --data "description=由 Gitlab 流水线自动发布的 Release, 构建产物请前往流水线下载" \
           --data "ref=main" \
           "https://gitlab.54sher.com/api/v4/projects/$CI_PROJECT_ID/releases"
    - echo "所有操作成功完成"
  dependencies:
    - build