// This file is auto-generated by @hey-api/openapi-ts

export const UserUpdateDTOSchema = {
    required: ['college', 'idNumber', 'name', 'phone', 'role'],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        idNumber: {
            type: 'string'
        },
        college: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        org: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseUserVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/UserVO'
        }
    }
} as const;

export const UserVOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        nickname: {
            type: 'string'
        },
        avatar: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        role: {
            type: 'string',
            enum: ['STUDENT', 'TEACHER', 'ADMIN', 'BANNED']
        },
        idNumber: {
            type: 'string'
        },
        college: {
            type: 'string'
        },
        org: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        count: {
            type: 'integer',
            format: 'int32'
        },
        isCompleted: {
            type: 'boolean'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        },
        bestRecord: {
            type: 'string'
        }
    }
} as const;

export const CheckInRequestSchema = {
    required: ['data', 'state', 'timestamp'],
    type: 'object',
    properties: {
        data: {
            type: 'string'
        },
        state: {
            type: 'string'
        },
        timestamp: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseRecordVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/RecordVO'
        }
    }
} as const;

export const RecordVOSchema = {
    type: 'object',
    properties: {
        status: {
            type: 'string',
            enum: ['PENDING', 'FINISHED', 'CANCELED']
        },
        progress: {
            type: 'integer',
            format: 'int32'
        },
        startTime: {
            type: 'string',
            format: 'date-time'
        },
        halfTime: {
            type: 'string',
            format: 'date-time'
        },
        endTime: {
            type: 'string',
            format: 'date-time'
        },
        isValid: {
            type: 'boolean'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        },
        totalMilliseconds: {
            type: 'string'
        }
    }
} as const;

export const WxConfigSchema = {
    type: 'object',
    properties: {
        appId: {
            type: 'string'
        },
        timestamp: {
            type: 'string'
        },
        nonceStr: {
            type: 'string'
        },
        signature: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseListRecordVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/RecordVO'
            }
        }
    }
} as const;

export const ApiResponseLeaderBoardVOUserCountLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/LeaderBoardVOUserCountLeaderBoardVO'
        }
    }
} as const;

export const LeaderBoardVOUserCountLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        leaderBoard: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UserCountLeaderBoardVO'
            }
        },
        lastUpdateTime: {
            type: 'string'
        }
    }
} as const;

export const UserCountLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        userName: {
            type: 'string'
        },
        userAvatar: {
            type: 'string'
        },
        userCount: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const ApiResponseLeaderBoardVOUserBestScoreLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/LeaderBoardVOUserBestScoreLeaderBoardVO'
        }
    }
} as const;

export const LeaderBoardVOUserBestScoreLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        leaderBoard: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UserBestScoreLeaderBoardVO'
            }
        },
        lastUpdateTime: {
            type: 'string'
        }
    }
} as const;

export const UserBestScoreLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        userName: {
            type: 'string'
        },
        userAvatar: {
            type: 'string'
        },
        userBestScore: {
            type: 'integer',
            format: 'int64'
        },
        userBestScoreFormatted: {
            type: 'string',
            readOnly: true
        }
    }
} as const;

export const ApiResponseLeaderBoardVOCollegeCountLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/LeaderBoardVOCollegeCountLeaderBoardVO'
        }
    }
} as const;

export const CollegeCountLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        collegeName: {
            type: 'string'
        },
        collegeCount: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const LeaderBoardVOCollegeCountLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        leaderBoard: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CollegeCountLeaderBoardVO'
            }
        },
        lastUpdateTime: {
            type: 'string'
        }
    }
} as const;