// This file is auto-generated by @hey-api/openapi-ts

export const UserUpdateDTOSchema = {
    required: ['college', 'nickname'],
    type: 'object',
    properties: {
        nickname: {
            type: 'string'
        },
        idNumber: {
            type: 'string'
        },
        college: {
            type: 'string'
        },
        phone: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseUserVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/UserVO'
        }
    }
} as const;

export const UserVOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        nickname: {
            type: 'string'
        },
        avatar: {
            type: 'string'
        },
        isBanned: {
            type: 'boolean'
        },
        idNumber: {
            type: 'string'
        },
        college: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        count: {
            type: 'integer',
            format: 'int32'
        },
        isCompleted: {
            type: 'boolean'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        },
        bestRecord: {
            type: 'string'
        }
    }
} as const;

export const CheckInRequestSchema = {
    required: ['data', 'state', 'timestamp'],
    type: 'object',
    properties: {
        data: {
            type: 'string'
        },
        state: {
            type: 'string'
        },
        timestamp: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseRecordVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/RecordVO'
        }
    }
} as const;

export const RecordVOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: ['PENDING', 'FINISHED', 'CANCELLED']
        },
        startTime: {
            type: 'string',
            format: 'date-time'
        },
        endTime: {
            type: 'string',
            format: 'date-time'
        },
        isValid: {
            type: 'boolean'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        },
        totalMilliseconds: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseFeedbackVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/FeedbackVO'
        }
    }
} as const;

export const FeedbackVOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        nickname: {
            type: 'string'
        },
        content: {
            type: 'string'
        },
        createTime: {
            type: 'integer',
            format: 'int64'
        },
        updateTime: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const ApiResponseWxConfigSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/WxConfig'
        }
    }
} as const;

export const WxConfigSchema = {
    type: 'object',
    properties: {
        appId: {
            type: 'string'
        },
        timestamp: {
            type: 'string'
        },
        nonceStr: {
            type: 'string'
        },
        signature: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseListRecordVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/RecordVO'
            }
        }
    }
} as const;

export const ApiResponseLeaderBoardVOUserCountLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/LeaderBoardVOUserCountLeaderBoardVO'
        }
    }
} as const;

export const LeaderBoardVOUserCountLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        leaderBoard: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UserCountLeaderBoardVO'
            }
        },
        lastUpdateTime: {
            type: 'string'
        }
    }
} as const;

export const UserCountLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        userName: {
            type: 'string'
        },
        userAvatar: {
            type: 'string'
        },
        userCount: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const ApiResponseLeaderBoardVOUserBestScoreLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/LeaderBoardVOUserBestScoreLeaderBoardVO'
        }
    }
} as const;

export const LeaderBoardVOUserBestScoreLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        leaderBoard: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UserBestScoreLeaderBoardVO'
            }
        },
        lastUpdateTime: {
            type: 'string'
        }
    }
} as const;

export const UserBestScoreLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        userName: {
            type: 'string'
        },
        userAvatar: {
            type: 'string'
        },
        userBestScore: {
            type: 'integer',
            format: 'int64'
        },
        userBestScoreFormatted: {
            type: 'string',
            readOnly: true
        }
    }
} as const;

export const ApiResponseLeaderBoardVOCollegeCountLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/LeaderBoardVOCollegeCountLeaderBoardVO'
        }
    }
} as const;

export const CollegeCountLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        collegeName: {
            type: 'string'
        },
        collegeCount: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const LeaderBoardVOCollegeCountLeaderBoardVOSchema = {
    type: 'object',
    properties: {
        leaderBoard: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CollegeCountLeaderBoardVO'
            }
        },
        lastUpdateTime: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseFeedbackVO__Schema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/FeedbackVO'
            }
        }
    }
} as const;

export const ApiResponseListCollegeVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CollegeVO'
            }
        }
    }
} as const;

export const CollegeVOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseListCheckPointSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CheckPoint'
            }
        }
    }
} as const;

export const CheckPointSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        isEnd: {
            type: 'boolean'
        },
        name: {
            type: 'string'
        },
        latitude: {
            type: 'number'
        },
        longitude: {
            type: 'number'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const ApiResponseStringSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            type: 'string'
        }
    }
} as const;