// This file is auto-generated by @hey-api/openapi-ts

export type UserUpdateDTO = {
    nickname: string;
    idNumber?: string;
    college: string;
    phone?: string;
};

export type ApiResponseUserVO = {
    code?: number;
    msg?: string;
    data?: UserVO;
};

export type UserVO = {
    id?: string;
    nickname?: string;
    avatar?: string;
    isBanned?: boolean;
    idNumber?: string;
    college?: string;
    phone?: string;
    count?: number;
    isCompleted?: boolean;
    createdAt?: string;
    updatedAt?: string;
    bestRecord?: string;
};

export type CheckInRequest = {
    data: string;
    state: string;
    timestamp: string;
};

export type ApiResponseRecordVO = {
    code?: number;
    msg?: string;
    data?: RecordVO;
};

export type RecordVO = {
    id?: string;
    status?: 'PENDING' | 'FINISHED' | 'CANCELLED';
    startTime?: string;
    endTime?: string;
    isValid?: boolean;
    createdAt?: string;
    updatedAt?: string;
    totalMilliseconds?: string;
};

export type status = 'PENDING' | 'FINISHED' | 'CANCELLED';

export type ApiResponseFeedbackVO = {
    code?: number;
    msg?: string;
    data?: FeedbackVO;
};

export type FeedbackVO = {
    id?: number;
    nickname?: string;
    content?: string;
    createTime?: number;
    updateTime?: number;
};

export type ApiResponseWxConfig = {
    code?: number;
    msg?: string;
    data?: WxConfig;
};

export type WxConfig = {
    appId?: string;
    timestamp?: string;
    nonceStr?: string;
    signature?: string;
};

export type ApiResponseListRecordVO = {
    code?: number;
    msg?: string;
    data?: Array<RecordVO>;
};

export type ApiResponseLeaderBoardVOUserCountLeaderBoardVO = {
    code?: number;
    msg?: string;
    data?: LeaderBoardVOUserCountLeaderBoardVO;
};

export type LeaderBoardVOUserCountLeaderBoardVO = {
    leaderBoard?: Array<UserCountLeaderBoardVO>;
    lastUpdateTime?: string;
};

export type UserCountLeaderBoardVO = {
    userName?: string;
    userAvatar?: string;
    userCount?: number;
};

export type ApiResponseLeaderBoardVOUserBestScoreLeaderBoardVO = {
    code?: number;
    msg?: string;
    data?: LeaderBoardVOUserBestScoreLeaderBoardVO;
};

export type LeaderBoardVOUserBestScoreLeaderBoardVO = {
    leaderBoard?: Array<UserBestScoreLeaderBoardVO>;
    lastUpdateTime?: string;
};

export type UserBestScoreLeaderBoardVO = {
    userName?: string;
    userAvatar?: string;
    userBestScore?: number;
    readonly userBestScoreFormatted?: string;
};

export type ApiResponseLeaderBoardVOCollegeCountLeaderBoardVO = {
    code?: number;
    msg?: string;
    data?: LeaderBoardVOCollegeCountLeaderBoardVO;
};

export type CollegeCountLeaderBoardVO = {
    collegeName?: string;
    collegeCount?: number;
};

export type LeaderBoardVOCollegeCountLeaderBoardVO = {
    leaderBoard?: Array<CollegeCountLeaderBoardVO>;
    lastUpdateTime?: string;
};

export type ApiResponseFeedbackVO__ = {
    code?: number;
    msg?: string;
    data?: Array<FeedbackVO>;
};

export type ApiResponseListCollegeVO = {
    code?: number;
    msg?: string;
    data?: Array<CollegeVO>;
};

export type CollegeVO = {
    id?: number;
    name?: string;
};

export type ApiResponseListCheckPoint = {
    code?: number;
    msg?: string;
    data?: Array<CheckPoint>;
};

export type CheckPoint = {
    id?: number;
    isEnd?: boolean;
    name?: string;
    latitude?: number;
    longitude?: number;
    createdAt?: string;
    updatedAt?: string;
};

export type ApiResponseString = {
    code?: number;
    msg?: string;
    data?: string;
};

export type UpdateApiData = {
    body: UserUpdateDTO;
};

export type UpdateApiResponse = (ApiResponseUserVO);

export type UpdateApiError = unknown;

export type LoginApiData = {
    query: {
        code: string;
    };
};

export type LoginApiResponse = (ApiResponseUserVO);

export type LoginApiError = unknown;

export type ListRecordResponse = (ApiResponseListRecordVO);

export type ListRecordError = unknown;

export type DoCheckinData = {
    body: CheckInRequest;
};

export type DoCheckinResponse = (ApiResponseRecordVO);

export type DoCheckinError = unknown;

export type GetFeedbackData = {
    query: {
        page: number;
        size: number;
    };
};

export type GetFeedbackResponse = (ApiResponseFeedbackVO);

export type GetFeedbackError = unknown;

export type AddFeedbackData = {
    body: string;
};

export type AddFeedbackResponse = (ApiResponseFeedbackVO);

export type AddFeedbackError = unknown;

export type GetWxConfigData = {
    query: {
        url: string;
    };
};

export type GetWxConfigResponse = (ApiResponseWxConfig);

export type GetWxConfigError = unknown;

export type InfoApiResponse = (ApiResponseUserVO);

export type InfoApiError = unknown;

export type GetLastRecordResponse = (ApiResponseRecordVO);

export type GetLastRecordError = unknown;

export type ListAllRecordResponse = (ApiResponseListRecordVO);

export type ListAllRecordError = unknown;

export type GetUserCountLeaderBoardResponse = (ApiResponseLeaderBoardVOUserCountLeaderBoardVO);

export type GetUserCountLeaderBoardError = unknown;

export type GetTop30UsersByBestScoreResponse = (ApiResponseLeaderBoardVOUserBestScoreLeaderBoardVO);

export type GetTop30UsersByBestScoreError = unknown;

export type GetCollegeLeaderBoardResponse = (ApiResponseLeaderBoardVOCollegeCountLeaderBoardVO);

export type GetCollegeLeaderBoardError = unknown;

export type ListCollegeApiResponse = (ApiResponseListCollegeVO);

export type ListCollegeApiError = unknown;

export type ListCheckPointResponse = (ApiResponseListCheckPoint);

export type ListCheckPointError = unknown;

export type CancelCheckinData = {
    path: {
        recordId: string;
    };
};

export type CancelCheckinResponse = (ApiResponseString);

export type CancelCheckinError = unknown;